### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by veeresh-dammur** [shreyasnayak/SimpleEncrypt#1]
Hi,
Thanks for the repo. Could you please check the below screenshot and let me know the cause of the installation error?
![image](https://user-images.githubusercontent.com/77052971/177585136-93a47394-722e-4929-8f16-bddfd6a7a04f.png)

Best, 
Veeresh

**Comment by shreyasnayak** [comment]
Hi Veeresh,

To use this SimpleEncrypt python library you need the C++ library to be compiled and installed.
Source code for C++ : https://github.com/shreyasnayak/SimpleEncrypt/tree/main/CPP ( Instruction are given in ReadMe page )

Once you run 'make install'  command this will copy linux shared lib libSimpleEncrypt.so to /usr/local/lib/ path

And i see you are trying this in Google Colab, i don't think you can build c++ library in google colab, Give a try in any linux computer

Thanks

**Comment by veeresh-dammur** [comment]
Thank you for the detailed response :)
